/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utils;

import Config.env;
import ConnectionCore.SendEmailThread;
import Datos.DComando;
import enums.HtmlVars;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;

public class HtmlBuilder {

    private static final String HTML_OPEN = "<!DOCTYPE html> <html lang=\"es\">";
    private static final String HTML_CLOSE = "</html>";
    private static final String HEAD_OPEN = "<head>";
    private static final String HEAD_CLOSE = "</head>";
    private static final String BODY_OPEN = "<body style=\"background: url(https://s3service12.s3.amazonaws.com/pattern.png);\n"
            + "  font-family: 'Roboto', sans-serif;\">";
    private static final String BODY_CLOSE = "</body>";

    public static final String MAIL_TO = SendEmailThread.USER + "@" + SendEmailThread.HOST;
    public static final String MAIL_ASUNTO = "list help[]";
    public static final String MAIL_ERROR = "Ocurrio un problema con el servidor: consulte a su proveedor";

    public static enum TYPE_TABLE_CONTENT {
        unico, muchos
    }

    private static String insertInHtml(String data) {
        return HTML_OPEN + BODY_OPEN + data + BODY_CLOSE + HTML_CLOSE;
    }

    public static String generateTable2(String title, String[] headers, List<String[]> data) {
        String body, head;
        String table_headers_html = "<tr>";
        for (String header : headers) {
            table_headers_html += "<th>" + header + "</th>";
        }
        table_headers_html += "</tr>";

        String table_body_html = "";
        for (String[] element : data) {
            table_body_html += "<tr>";
            for (String value : element) {
                table_body_html += "<td>" + value + "</td>";
            }
            table_body_html += "</tr>";
        }
        head = "  <meta charset=\"utf-8\">\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, user-scalable=no\">\n"
                + "  <title>Fixed table header</title>\n"
                + "  <style type=\"text/css\">\n"
                + "    * {\n"
                + "      margin: 0px;\n"
                + "      padding: 0px;\n"
                + "    }\n"
                + "\n"
                + "    section {\n"
                + "      margin: 50px;\n"
                + "    }\n"
                + "\n"
                + "    h1 {\n"
                + "      font-size: 30px;\n"
                + "      color: #ccc;\n"
                + "      text-transform: uppercase;\n"
                + "      font-weight: 300;\n"
                + "      text-align: center;\n"
                + "      margin: 15px;\n"
                + "    }\n"
                + "\n"
                + "    .wrap {\n"
                + "      width: 1250px;\n"
                + "      margin: 0px auto;\n"
                + "      padding-bottom: 20px;\n"
                + "    }\n"
                + "\n"
                + "    #banner {\n"
                + "      width: 95.5%;\n"
                + "      height: 100px;\n"
                + "      border: 10px solid black;\n"
                + "      box-shadow: 0px 0px 15px black;\n"
                + "      background: url(\"" + HtmlVars.BG_IMG + "\");\n"
                + "      background-position: -200px -200px;\n"
                + "      margin: 20px auto;\n"
                + "      overflow: hidden;\n"
                + "    }\n"
                + "\n"
                + "    #banner h1 {\n"
                + "      display: block;\n"
                + "      width: 850px;\n"
                + "      font-family: \"BebasNeue\";\n"
                + "      color: white;\n"
                + "      font-size: 45px;\n"
                + "      font-weight: normal;\n"
                + "      letter-spacing: 2px;\n"
                + "      text-shadow: 2px 2px 1px black;\n"
                + "      margin: 27px auto;\n"
                + "    }\n"
                + "\n"
                + "    #titulo {\n"
                + "      height: 280px;\n"
                + "    }\n"
                + "\n"
                + "    #titulo img {\n"
                + "      height: 250px;\n"
                + "      display: block;\n"
                + "      margin: 0 auto;\n"
                + "      border: 5px solid black;\n"
                + "      border-radius: 25px;\n"
                + "    }\n"
                + "\n"
                + "    table {\n"
                + "      width: 100%;\n"
                + "      table-layout: fixed;\n"
                + "      border-collapse: collapse;\n"
                + "      margin: 0;\n"
                + "      padding: 0;\n"
                + "    }\n"
                + "\n"
                + "    th {\n"
                + "      padding: 20px 15px;\n"
                + "      text-align: left;\n"
                + "      font-weight: 500;\n"
                + "      font-size: 20px;\n"
                + "      color: white;\n"
                + "      text-transform: uppercase;\n"
                + "    }\n"
                + "\n"
                + "    td {\n"
                + "      padding: 15px;\n"
                + "      text-align: left;\n"
                + "      vertical-align: middle;\n"
                + "      font-weight: 300;\n"
                + "      font-size: 18px;\n"
                + "      color: black;\n"
                + "      border-bottom: solid 1px black;\n"
                + "    }\n"
                + "\n"
                + "    .tbl-header {\n"
                + "      padding-top: 10px;\n"
                + "      background-color: black;\n"
                + "    }\n"
                + "\n"
                + "    .tbl-content {\n"
                + "      height: 310px;\n"
                + "      overflow-x: auto;\n"
                + "      border: 3px solid black;\n"
                + "      background-color: #f8f8f8;\n"
                + "    }\n"
                + "\n"
                + "    .clearfix {\n"
                + "      float: none;\n"
                + "      clear: both;\n"
                + "    }\n"
                + "\n"
                + "    #footer .wrap>div {\n"
                + "      float: left;\n"
                + "      width: 320px;\n"
                + "      height: 370px;\n"
                + "      margin: 40px;\n"
                + "      text-align: center;\n"
                + "      color: white;\n"
                + "    }\n"
                + "\n"
                + "    #footer {\n"
                + "      width: 100%;\n"
                + "      height: 470px;\n"
                + "      background: black;\n"
                + "      color: white;\n"
                + "      overflow: hidden;\n"
                + "    }\n"
                + "\n"
                + "\n"
                + "    #footer a {\n"
                + "      text-decoration: none;\n"
                + "      color: #37bcf9;\n"
                + "      transition: all 300ms;\n"
                + "\n"
                + "    }\n"
                + "\n"
                + "    #footer h5 {\n"
                + "      display: block;\n"
                + "      background: white;\n"
                + "      height: 50px;\n"
                + "      letter-spacing: 2px;\n"
                + "      text-align: center;\n"
                + "      font-size: 25px;\n"
                + "      line-height: 55px;\n"
                + "      color: black;\n"
                + "      border-radius: 5px;\n"
                + "      margin-bottom: 15px;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul {\n"
                + "      text-align: left;\n"
                + "      margin: 20px;\n"
                + "      font-size: 25px;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul li {\n"
                + "      margin-top: 10px;\n"
                + "      padding: 5px;\n"
                + "      border-bottom: 1px solid #ccc;\n"
                + "    }\n"
                + "\n"
                + "    #footer img {\n"
                + "      margin-bottom: 15px;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul li a {\n"
                + "      display: block;\n"
                + "      height: 40px;\n"
                + "      transition: all 300ms;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul li:hover a {\n"
                + "      padding-left: 40px;\n"
                + "      color: white;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    #footer #browsers img {\n"
                + "      width: 45px;\n"
                + "    }\n"
                + "\n"
                + "    #info img {\n"
                + "      width: 150px;\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width:1250px) {\n"
                + "\n"
                + "      .wrap {\n"
                + "        width: 90%;\n"
                + "        margin: 0px auto;\n"
                + "      }\n"
                + "\n"
                + "      #footer .wrap>div {\n"
                + "        width: 25%;\n"
                + "      }\n"
                + "\n"
                + "      #footer h5 {\n"
                + "        font-size: 30px;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 1080px) {\n"
                + "      #footer .wrap>div {\n"
                + "        width: 22%;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 970px) {\n"
                + "      #footer .wrap>div {\n"
                + "        width: 26%;\n"
                + "        margin: 20px;\n"
                + "\n"
                + "      }\n"
                + "\n"
                + "      #footer h5 {\n"
                + "        font-size: 22px;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 799px) {\n"
                + "      #banner h1 {\n"
                + "        font-size: 30px;\n"
                + "        display: block;\n"
                + "        text-align: center;\n"
                + "      }\n"
                + "\n"
                + "      #banner h1 {\n"
                + "        width: 200px;\n"
                + "      }\n"
                + "\n"
                + "      .card {\n"
                + "        height: auto;\n"
                + "      }\n"
                + "\n"
                + "      #footer img {\n"
                + "        margin-bottom: 15px;\n"
                + "        max-width: 100%;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 600px) {\n"
                + "      #footer {\n"
                + "        height: auto;\n"
                + "        padding-bottom: 40px;\n"
                + "      }\n"
                + "\n"
                + "      #footer .wrap>div {\n"
                + "        width: 100%;\n"
                + "        margin: 0px auto;\n"
                + "        margin-top: 20px;\n"
                + "      }\n"
                + "\n"
                + "      #footer h5 {\n"
                + "        font-size: 25px;\n"
                + "      }\n"
                + "\n"
                + "      .tbl-content table tr {\n"
                + "        display: block;\n"
                + "        border-bottom: 5px solid black;\n"
                + "        background-color: #f8f8f8;\n"
                + "      }\n"
                + "\n"
                + "      .tbl-content table td {\n"
                + "        display: block;\n"
                + "        text-align: right;\n"
                + "        border-bottom: 1px solid #ddd;\n"
                + "      }\n"
                + "\n"
                + "    }\n"
                + "  </style>";

        body = "  <section class=\"wrap\">\n"
                + "\n"
                + "    <div id=\"banner\">\n"
                + "      <h1>" + HtmlVars.TITULO_SW + "</h1>\n"
                + "    </div>\n"
                + "\n"
                + "    <div id=\"titulo\">\n"
                + "<P>DONDE VA ESTO????????</p>"
                + "      <img\n"
                + "        src=\"https://scontent.fvvi1-1.fna.fbcdn.net/v/t1.18169-9/14691012_547821868741019_5762955511133398050_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=bC-X6Iq9JosAX_Dw2TK&_nc_ht=scontent.fvvi1-1.fna&oh=00_AfC1wvJIHEGl1RNRO1M7dc-hSOxRhU5Xr4v5Ef23NXqZyA&oe=6392475A\"\n"
                + "        alt=\"\">\n"
                + "    </div>\n"
                + "\n"
                + "    <div class=\"tbl-header\">\n"
                + "      <h1>" + title + "</h1>\n"
                + "      <table>\n"
                + "        <thead>\n"
                + table_headers_html
                + "        </thead>\n"
                + "      </table>\n"
                + "    </div>\n"
                + "\n"
                + "    <div class=\"tbl-content\">\n"
                + "      <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
                + "        <tbody>\n"
                + table_body_html
                + "        </tbody>\n"
                + "      </table>\n"
                + "    </div>\n"
                + "  </section>\n"
                + "\n"
                + "\n"
                + "  <div class=\"clearfix\"></div>\n"
                + "\n"
                + "  <footer id=\"footer\">\n"
                + "    <div class=\"wrap\">\n"
                + "      <div id=\"menu_footer\">\n"
                + "        <h5>MENÚ</h5>\n"
                + "        <ul>\n"
                + "          <li> <a href=\"#\">Inicio</a> </li>\n"
                + "          <li> <a href=\"#\">Blog</a> </li>\n"
                + "          <li> <a href=\"#\">Formacion</a> </li>\n"
                + "          <li> <a href=\"#\">Contacto</a> </li>\n"
                + "        </ul>\n"
                + "      </div>\n"
                + "\n"
                + "      <div id=\"location\">\n"
                + "        <h5>¿DONDE ESTAMOS?</h5>\n"
                // + " <img height=\"250\" width=\"100%\"
                // src=\"https://s3service12.s3.amazonaws.com/1/11.png\" alt=\"ubicacion\">\n"
                + "        <a\n"
                + "          href=\"https://www.google.com/maps/place/Clinica+Medica+La+Guardia+SRL/@-17.8919593,-63.6264264,11z/data=!4m6!3m5!1s0x93f1c7b182e8058f:0x7d38e4efccf1f12d!8m2!3d-17.8919593!4d-63.3215558!16s%2Fg%2F11m_lhnvfg?entry=ttu\">click\n"
                + "          ubicacion\n"
                + "        </a>\n"
                + "      </div>\n"
                + "\n"
                + "      <div id=\"info\">\n"
                + "        <h5>Desarollado con</h5>\n"
                + "        <p>\n"
                + "          <img src=\"https://www.pikpng.com/pngl/m/150-1506141_html-css-and-javascript-logo-html5-css3-js.png\"\n"
                + "            alt=\"Creado con HTML y CSS\">\n"
                + "        </p>\n"
                + "\n"
                + "        <h5>Optimizado para</h5>\n"
                + "        <p id=\"browsers\">\n"
                + "          <a href=\"#\">\n"
                + "            <img src=\"https://www.freeiconspng.com/thumbs/mozilla-firefox-icon/mozilla-firefox-icon-4.png\" alt=\"Firefox\"\n"
                + "              title=\"Firefox\">\n"
                + "          </a>\n"
                + "\n"
                + "          <a href=\"#\">\n"
                + "            <img src=\"https://www.freeiconspng.com/uploads/google-chrome-icon-6.png\" alt=\"Crome\" title=\"Crome\">\n"
                + "          </a>\n"
                + "\n"
                + "          <a href=\"#\">\n"
                + "            <img src=\"https://cdn-icons-png.flaticon.com/512/6124/6124992.png\" alt=\"Safari\" title=\"Safari\">\n"
                + "          </a>\n"
                + "\n"
                + "          <a href=\"#\">\n"
                + "            <img src=\"https://cdn-icons-png.flaticon.com/512/226/226770.png\" alt=\"android\" title=\"android\">\n"
                + "          </a>\n"
                + "\n"
                + "          <a href=\"#\">\n"
                + "            <img src=\"https://www.freeiconspng.com/thumbs/ios-png/os7-style-metro-ui-icon-19.png\" alt=\"Apple\"\n"
                + "              title=\"Apple\">\n"
                + "          </a>\n"
                + "\n"
                + "        </p>\n"
                + "\n"
                + "        <h5>AUTOR</h5>\n"
                + "        <p>&copy; GRUPO-21-SA 2023/2 - WEB.es</p>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "  </footer>";
        return HTML_OPEN + HEAD_OPEN + head + HEAD_CLOSE + BODY_OPEN + body + BODY_CLOSE + HTML_CLOSE;

    }

    public static String generateMessageInfo(String message, String btnMailTo, String btnSubject) {
        String typeMessage = ""
                + "      color: #00529B;\n"
                + "      background-color: #BDE5F8;\n"
                + "      background-image: url('https://www.freeiconspng.com/uploads/information-icon--14.png');\n";
        return generateMessage(message, btnMailTo, btnSubject, typeMessage);
    }

    public static String generateMessageCorrecto(String message, String btnMailTo, String btnSubject) {
        String typeMessage = " color: #4F8A10;\n"
                + "      background-color: #DFF2BF;\n"
                + "      background-image: url('https://www.jose-aguilar.com/blog/wp-content/uploads/2011/09/correcto.jpg');";
        return generateMessage(message, btnMailTo, btnSubject, typeMessage);
    }

    public static String generateMessageError(String message, String btnMailTo, String btnSubject) {
        String typeMessage = "color: #D8000C;\n"
                + "      background-color: #FFBABA;\n"
                + "      background-image: url('https://www.freeiconspng.com/uploads/sign-red-error-icon-1.png');";
        return generateMessage(message, btnMailTo, btnSubject, typeMessage);
    }

    public static String generateMessageOjo(String message, String btnMailTo, String btnSubject) {
        String typeMessage = "color: #9F6000;\n"
                + "      background-color: #FEEFB3;\n"
                + "      background-image: url('https://www.freeiconspng.com/uploads/error-icon-3.png');";
        return generateMessage(message, btnMailTo, btnSubject, typeMessage);
    }

    private static String generateMessage(String message, String btnMailTo, String btnSubject, String typeMessage) {
        String head, body, solicitar_comandos;
        solicitar_comandos = HtmlBuilder.generateMailToComand();
        head = " <meta charset=\"utf-8\">\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, user-scalable=no\">\n"
                + "  <title>Fixed table header</title>\n"
                + "  <style type=\"text/css\">\n"
                + "    * {\n"
                + "      margin: 0px;\n"
                + "      padding: 0px;\n"
                + "    }\n"
                + "\n"
                + "    section {\n"
                + "      margin: 50px;\n"
                + "    }\n"
                + "\n"
                + "    h1 {\n"
                + "      font-size: 30px;\n"
                + "      color: #ccc;\n"
                + "      text-transform: uppercase;\n"
                + "      font-weight: 300;\n"
                + "      text-align: center;\n"
                + "      margin: 15px;\n"
                + "    }\n"
                + "\n"
                + "    .wrap {\n"
                + "      width: 1250px;\n"
                + "      margin: 0px auto;\n"
                + "      padding-bottom: 20px;\n"
                + "    }\n"
                + "\n"
                + "    #banner {\n"
                + "      width: 95.5%;\n"
                + "      height: 100px;\n"
                + "      border: 10px solid black;\n"
                + "      box-shadow: 0px 0px 15px black;\n"
                + "      background: url(\"https://s3service12.s3.amazonaws.com/bakbaner.png\");\n"
                + "      background-position: -200px -200px;\n"
                + "      margin: 20px auto;\n"
                + "      overflow: hidden;\n"
                + "    }\n"
                + "\n"
                + "    #banner h1 {\n"
                + "      display: block;\n"
                + "      width: 850px;\n"
                + "      font-family: \"BebasNeue\";\n"
                + "      color: white;\n"
                + "      font-size: 45px;\n"
                + "      font-weight: normal;\n"
                + "      letter-spacing: 2px;\n"
                + "      text-shadow: 2px 2px 1px black;\n"
                + "      margin: 27px auto;\n"
                + "    }\n"
                + "\n"
                + "    #titulo {\n"
                + "      height: 280px;\n"
                + "    }\n"
                + "\n"
                + "    #titulo img {\n"
                + "      height: 250px;\n"
                + "      display: block;\n"
                + "      margin: 0 auto;\n"
                + "      border: 5px solid black;\n"
                + "      border-radius: 25px;\n"
                + "    }\n"
                + "\n"
                + "    .message {\n"
                + "      display: block;\n"
                + "      margin: auto;\n"
                + "      width: 70%;\n"
                + "      overflow: auto;\n"
                + "      border: 2px solid;\n"
                + "      padding: 15px 10px 15px 75px;\n"
                + "      background-repeat: no-repeat;\n"
                + "      background-position: 10px center;\n"
                + "      font-family: Arial, Helvetica, sans-serif;\n"
                + "      font-size: 25px;\n"
                + "      text-align: left;\n"
                + "      background-size: 2.8%;\n"
                + "      \n"
                + typeMessage
                + "    }\n"
                + "\n"
                + "    .email {\n"
                + "      margin: 30px;\n"
                + "    }\n"
                + "    \n"
                + "    #email {\n"
                + "      display: block;\n"
                + "      margin: auto;\n"
                + "      width: 200px;\n"
                + "      background: black;\n"
                + "      color: #fff;\n"
                + "      padding: 5px 10px;\n"
                + "      text-align: center;\n"
                + "      font-size: 20px;\n"
                + "      text-decoration: none;\n"
                + "      border: 3px solid gray;\n"
                + "      border-radius: 10cm;\n"
                + "    }\n"
                + "    \n"
                + "    .clearfix {\n"
                + "      float: none;\n"
                + "      clear: both;\n"
                + "    }\n"
                + "\n"
                + "    #footer .wrap>div {\n"
                + "      float: left;\n"
                + "      width: 320px;\n"
                + "      height: 370px;\n"
                + "      margin: 40px;\n"
                + "      text-align: center;\n"
                + "      color: white;\n"
                + "    }\n"
                + "\n"
                + "    #footer {\n"
                + "      width: 100%;\n"
                + "      height: 470px;\n"
                + "      background: black;\n"
                + "      color: white;\n"
                + "      overflow: hidden;\n"
                + "    }\n"
                + "\n"
                + "\n"
                + "    #footer a {\n"
                + "      text-decoration: none;\n"
                + "      color: #37bcf9;\n"
                + "      transition: all 300ms;\n"
                + "\n"
                + "    }\n"
                + "\n"
                + "    #footer h5 {\n"
                + "      display: block;\n"
                + "      background: white;\n"
                + "      height: 50px;\n"
                + "      letter-spacing: 2px;\n"
                + "      text-align: center;\n"
                + "      font-size: 25px;\n"
                + "      line-height: 55px;\n"
                + "      color: black;\n"
                + "      border-radius: 5px;\n"
                + "      margin-bottom: 15px;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul {\n"
                + "      text-align: left;\n"
                + "      margin: 20px;\n"
                + "      font-size: 25px;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul li {\n"
                + "      margin-top: 10px;\n"
                + "      padding: 5px;\n"
                + "      border-bottom: 1px solid #ccc;\n"
                + "    }\n"
                + "\n"
                + "    #footer img {\n"
                + "      margin-bottom: 15px;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul li a {\n"
                + "      display: block;\n"
                + "      height: 40px;\n"
                + "      transition: all 300ms;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul li:hover a {\n"
                + "      padding-left: 40px;\n"
                + "      color: white;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    #footer #browsers img {\n"
                + "      width: 45px;\n"
                + "    }\n"
                + "\n"
                + "    #info img {\n"
                + "      width: 150px;\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width:1250px) {\n"
                + "\n"
                + "      .wrap {\n"
                + "        width: 90%;\n"
                + "        margin: 0px auto;\n"
                + "      }\n"
                + "\n"
                + "      #footer .wrap>div {\n"
                + "        width: 25%;\n"
                + "      }\n"
                + "\n"
                + "      #footer h5 {\n"
                + "        font-size: 30px;\n"
                + "      }\n"
                + "      .message{\n"
                + "        font-size: 22px;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 1080px) {\n"
                + "      #footer .wrap>div {\n"
                + "        width: 22%;\n"
                + "      }\n"
                + "      .message {\n"
                + "        background-size: 4%;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 970px) {\n"
                + "      #footer .wrap>div {\n"
                + "        width: 26%;\n"
                + "        margin: 20px;\n"
                + "\n"
                + "      }\n"
                + "\n"
                + "      #footer h5 {\n"
                + "        font-size: 22px;\n"
                + "      }\n"
                + "\n"
                + "      .message {\n"
                + "        background-size: 5%;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 799px) {\n"
                + "      #banner h1 {\n"
                + "        font-size: 30px;\n"
                + "        display: block;\n"
                + "        text-align: center;\n"
                + "      }\n"
                + "\n"
                + "      #banner h1 {\n"
                + "        width: 200px;\n"
                + "      }\n"
                + "\n"
                + "      .card {\n"
                + "        height: auto;\n"
                + "      }\n"
                + "\n"
                + "      #footer img {\n"
                + "        margin-bottom: 15px;\n"
                + "        max-width: 100%;\n"
                + "      }\n"
                + "\n"
                + "      .message {\n"
                + "        background-size: 7%;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 600px) {\n"
                + "      #footer {\n"
                + "        height: auto;\n"
                + "        padding-bottom: 40px;\n"
                + "      }\n"
                + "\n"
                + "      #footer .wrap>div {\n"
                + "        width: 100%;\n"
                + "        margin: 0px auto;\n"
                + "        margin-top: 20px;\n"
                + "      }\n"
                + "\n"
                + "      #footer h5 {\n"
                + "        font-size: 25px;\n"
                + "      }\n"
                + "\n"
                + "      .message {\n"
                + "        background-size: 8%;\n"
                + "      }\n"
                + "    }\n"
                + "  </style>";
        // body-----------------------------------------
        body = "<section class=\"wrap\">\n"
                + "\n"
                + "    <div id=\"banner\">\n"
                + "      <h1>" + HtmlVars.TITULO_SW + "</h1>\n"
                + "    </div>\n"
                + "\n"
                + "    <div id=\"titulo\">\n"
                + "      <img\n"
                + "        src=\"https://scontent.fvvi1-1.fna.fbcdn.net/v/t1.18169-9/14691012_547821868741019_5762955511133398050_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=bC-X6Iq9JosAX_Dw2TK&_nc_ht=scontent.fvvi1-1.fna&oh=00_AfC1wvJIHEGl1RNRO1M7dc-hSOxRhU5Xr4v5Ef23NXqZyA&oe=6392475A\"\n"
                + "        alt=\"\">\n"
                + "    </div>\n"
                + "    <div class=\"message\"><b>" + message + "</b></div>\n"
                + "    <div class=\"email\">\n"
                + "      <a id=\"email\" type=\"submit\" href=\"mailto:" + btnMailTo + "?Subject=" + btnSubject
                + "\">Solicitar Comandos</a>\n"
                + "    </div>\n"
                + "  </section>\n"
                + "\n"
                + "\n"
                + "  <div class=\"clearfix\"></div>\n"
                + "\n"
                + "  <footer id=\"footer\">\n"
                + "    <div class=\"wrap\">\n"
                + "      <div id=\"menu_footer\">\n"
                + "        <h5>MENÚ</h5>\n"
                + "        <ul>\n"
                + "          <li> <a href=\"" + solicitar_comandos + "\">Solicitar Comandos</a> </li>\n"
                + "          <li> <a href=\"#\">Blog</a> </li>\n"
                + "          <li> <a href=\"#\">Formacion</a> </li>\n"
                + "          <li> <a href=\"#\">Contacto</a> </li>\n"
                + "        </ul>\n"
                + "      </div>\n"
                + "\n"
                + "      <div id=\"location\">\n"
                + "        <h5>¿DONDE ESTAMOS?</h5>\n"
                + "        <img height=\"250\" width=\"100%\" src=\"https://s3service12.s3.amazonaws.com/1/11.png\" alt=\"ubicacion\">\n"
                + "        <a\n"
                + "          href=\"https://www.google.com/maps/place/Clinica+Medica+La+Guardia+SRL/@-17.8919593,-63.6264264,11z/data=!4m6!3m5!1s0x93f1c7b182e8058f:0x7d38e4efccf1f12d!8m2!3d-17.8919593!4d-63.3215558!16s%2Fg%2F11m_lhnvfg?entry=ttu\">click\n"
                + "          ubicacion\n"
                + "        </a>\n"
                + "      </div>\n"
                + "\n"
                + "      <div id=\"info\">\n"
                + "        <h5>Desarollado con</h5>\n"
                + "        <p>\n"
                + "          <img src=\"https://www.pikpng.com/pngl/m/150-1506141_html-css-and-javascript-logo-html5-css3-js.png\"\n"
                + "            alt=\"Creado con HTML y CSS\">\n"
                + "        </p>\n"
                + "\n"
                + "        <h5>Optimizado para</h5>\n"
                + "        <p id=\"browsers\">\n"
                + "          <a href=\"#\">\n"
                + "            <img src=\"https://www.freeiconspng.com/thumbs/mozilla-firefox-icon/mozilla-firefox-icon-4.png\" alt=\"Firefox\"\n"
                + "              title=\"Firefox\">\n"
                + "          </a>\n"
                + "\n"
                + "          <a href=\"#\">\n"
                + "            <img src=\"https://www.freeiconspng.com/uploads/google-chrome-icon-6.png\" alt=\"Crome\" title=\"Crome\">\n"
                + "          </a>\n"
                + "\n"
                + "          <a href=\"#\">\n"
                + "            <img src=\"https://cdn-icons-png.flaticon.com/512/6124/6124992.png\" alt=\"Safari\" title=\"Safari\">\n"
                + "          </a>\n"
                + "\n"
                + "          <a href=\"#\">\n"
                + "            <img src=\"https://cdn-icons-png.flaticon.com/512/226/226770.png\" alt=\"android\" title=\"android\">\n"
                + "          </a>\n"
                + "\n"
                + "          <a href=\"#\">\n"
                + "            <img src=\"https://www.freeiconspng.com/thumbs/ios-png/os7-style-metro-ui-icon-19.png\" alt=\"Apple\"\n"
                + "              title=\"Apple\">\n"
                + "          </a>\n"
                + "\n"
                + "        </p>\n"
                + "\n"
                + "        <h5>AUTOR</h5>\n"
                + "        <p>&copy; GRUPO-21-SA 2022/2 - WEB.es</p>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "  </footer>";
        return HTML_OPEN + HEAD_OPEN + head + HEAD_CLOSE + BODY_OPEN + body + BODY_CLOSE + HTML_CLOSE;
    }

    public static String generateComandos() {
        String titulo, resultado;
        String[] cabecera;
        try {
            titulo = "MANUAL DE EMAIL SYSTEM TECNOWEB: \"" + HtmlVars.TITULO_SW + "\"";
            cabecera = new String[] { "CASO DE USO", "DESC", "PARÁMETROS", "EJEMPLO", "ACCION" };
            resultado = HtmlBuilder.generateTable(titulo, cabecera, DComando.listarComplete());
        } catch (SQLException e) {
            System.out.println("generateComand" + e.getMessage());
            resultado = HtmlBuilder.generateMessageError(
                    HtmlBuilder.MAIL_ERROR,
                    HtmlBuilder.MAIL_TO,
                    HtmlBuilder.MAIL_ASUNTO);
        }
        return resultado;
    }

    public static String generateTableUniqueDate(String title, String[] headers, String[] data) {
        List<String[]> d = new LinkedList();
        d.add(data);
        return generateTable(title, headers, d, TYPE_TABLE_CONTENT.unico);
    }

    public static String generateTable(String title, String[] headers, List<String[]> data) {
        return generateTable(title, headers, data, TYPE_TABLE_CONTENT.muchos);
    }

    private static String generateMailToComand() {
        String solicitar_comandos, mailto, subject, res;
        mailto = env.EMAIL_SERVER;
        subject = ResStatus.__HELP;
        res = "";
        /* Href = "solicitar comandos" */
        solicitar_comandos = "mailto:" + mailto + "?subject=" + subject + "&body=" + res;
        return solicitar_comandos;
    }

    private static String generateTableHeaders(String[] headers) {
        String table_headers_html = "<tr>";
        for (String header : headers) {
            table_headers_html += "<th>" + header + "</th>";
        }
        table_headers_html += "</tr>";
        return table_headers_html;
    }

    private static String generateTableBody(List<String[]> data) {
        String table_body_html = "";
        for (String[] element : data) {
            table_body_html += "<tr>";
            for (String value : element) {
                table_body_html += "<td>" + value + "</td>";
            }
            table_body_html += "</tr>";
        }
        return table_body_html;
    }

    private static String generateTable(String title, String[] headers, List<String[]> data,
            TYPE_TABLE_CONTENT typeTableContent) {
        String body, head, solicitar_comandos, tableHeight;

        solicitar_comandos = HtmlBuilder.generateMailToComand(); // "href=#"
        String table_headers_html = HtmlBuilder.generateTableHeaders(headers);
        String table_body_html = HtmlBuilder.generateTableBody(data);
        tableHeight = (typeTableContent == TYPE_TABLE_CONTENT.unico)
                ? ""
                : "height: 700px;\n";

        head = "<style type=\"text/css\">\n"
                + "    * {\n"
                + "      margin: 0px;\n"
                + "      padding: 0px;\n"
                + "    }\n"
                + "\n"
                + "    section {\n"
                + "      margin: 50px;\n"
                + "    }\n"
                + "\n"
                + "    h1 {\n"
                + "      font-size: 30px;\n"
                + "      color: #ccc;\n"
                + "      text-transform: uppercase;\n"
                + "      font-weight: 300;\n"
                + "      text-align: center;\n"
                + "      margin: 15px;\n"
                + "    }\n"
                + "\n"
                + "    .wrap {\n"
                + "      /* width: 1250px; */\n"
                + "      width: 90%;\n"
                + "      margin: 0px auto;\n"
                + "      padding-bottom: 20px;\n"
                + "    }\n"
                + "\n"
                + "    #banner {\n"
                + "      width: 100%;\n"
                + "      display: flex;\n"
                + "      flex-direction: column;\n"
                + "      justify-items: center;\n"
                + "      align-items: center;\n"
                + "      text-align: center;\n"
                + "      color: " + HtmlVars.BLUE_COLOR+ ";\n"
                + "      border: 1px solid black;\n"
//                + "      background: url(\""+ HtmlVars.BG_IMG +"\");\n"
//                + "      background-position: -200px -200px;\n"
                + "      margin: 20px 0px;\n"
                + "      overflow: hidden;\n"
                + "    }\n"
                + "\n"
                + "    #banner h1 {\n"
                + "      font-family: monospace;"
                + "      font-family: \"BebasNeue\";\n"
                + "      font-size: 15px;\n"
                + "      font-weight: bold;\n"
                + "      letter-spacing: 7px;\n"
//                + "      margin: 15px auto;\n"
                + "    }\n"
                + "\n"
                + "     .banner-photo {\n"
                + "         height: 200px;"
                + "         background: url(\""+ HtmlVars.BG_IMG +"\");\n"
                + "         width: 100%;"
                + "     }"
                + "\n"
                + "    table {\n"
                + "      width: 100%;\n"
                + "      table-layout: fixed;\n"
                + "      border-collapse: collapse;\n"
                + "      margin: 0;\n"
                + "      padding: 0;\n"
                + "    }\n"
                + "\n"
                + "    th {\n"
                + "      overflow-x: auto;\n"
                + "      padding: 20px 15px;\n"
                + "      text-align: left;\n"
                + "      font-weight: 500;\n"
                + "      font-size: 20px;\n"
                + "      color: white;\n"
                + "      text-transform: uppercase;\n"
                + "    }\n"
                + "\n"
                + "    td {\n"
                + "      padding: 15px;\n"
                + "      text-align: left;\n"
                + "      vertical-align: middle;\n"
                + "      font-weight: 300;\n"
                + "      font-size: 18px;\n"
                + "      color: black;\n"
                + "      border-bottom: solid 1px black;\n"
                + "    }\n"
                + "\n"
                + "    .tbl-header {\n"
                + "      display: block;\n"
                + "      overflow-y: auto;\n"
                + "      padding-top: 10px;\n"
                + "      background-color: " + HtmlVars.BLUE_COLOR +";\n"
                + "    }\n"
                + "\n"
                + "    .tbl-content {\n"
                + "      display: block;\n"
                + "      overflow-x: auto;\n"
                + tableHeight
                + "      border: 1px solid black;\n"
                + "      background-color: #f8f8f8;\n"
                + "    }\n"
                + "\n"
                + "    .class-button {\n"
                + "      margin: 5px;\n"
                + "      padding: 10px;\n"
                + "      border-radius: 10cm;\n"
                + "      border: 1px solid black;\n"
                + "      text-decoration: none;\n"
                + "      display: inline-block;\n"
                + "      background: "+HtmlVars.GREEN_COLOR+";\n"
                + "      text-align: center;\n"
                + "      line-height: 2;\n"
                + "      color: white;\n"
                + "    }\n"
                + "\n"
                + "    .clearfix {\n"
                + "      float: none;\n"
                + "      clear: both;\n"
                + "    }\n"
                + "\n"
                + "    #footer {\n"
                + "      width: 100%;\n"
                + "      height: 470px;\n"
                + "      background: black;\n"
                + "      color: white;\n"
                + "      overflow: hidden;\n"
                + "      margin-top: 20px;\n"
                + "    }\n"
                + "\n"
                + "    #footer .wrap>div {\n"
                + "      float: left;\n"
                + "      width: 30%;\n"
                + "      /* width: 300px; */\n"
                + "      /* height: 370px; */\n"
                + "      margin: 3% 1%;\n"
                + "      /* margin: 60px 40px; */\n"
                + "      text-align: center;\n"
                + "      color: white;\n"
                + "    }\n"
                + "\n"
                + "\n"
                + "\n"
                + "    #footer a {\n"
                + "      text-decoration: none;\n"
                + "      color: #37bcf9;\n"
                + "      transition: all 300ms;\n"
                + "    }\n"
                + "\n"
                + "    #footer h5 {\n"
                + "      display: block;\n"
                + "      background: white;\n"
                + "      height: 50px;\n"
                + "      letter-spacing: 2px;\n"
                + "      text-align: center;\n"
                + "      font-size: 25px;\n"
                + "      line-height: 55px;\n"
                + "      color: black;\n"
                + "      border-radius: 5px;\n"
                + "      margin-bottom: 15px;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul {\n"
                + "      text-align: left;\n"
                + "      margin: 20px;\n"
                + "      font-size: 25px;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul li {\n"
                + "      margin-top: 10px;\n"
                + "      padding: 5px;\n"
                + "      border-bottom: 1px solid #ccc;\n"
                + "    }\n"
                + "\n"
                + "    #footer img {\n"
                + "      margin-bottom: 15px;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul li a {\n"
                + "      display: block;\n"
                + "      height: 40px;\n"
                + "      transition: all 300ms;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul li:hover a {\n"
                + "      padding-left: 40px;\n"
                + "      color: white;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    #footer #browsers img {\n"
                + "      width: 45px;\n"
                + "    }\n"
                + "\n"
                + "    #info img {\n"
                + "      width: 150px;\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width:1500px) {\n"
                + "      .wrap {\n"
                + "        width: 90%;\n"
                + "        margin: 0px auto;\n"
                + "      }\n"
                + "\n"
                + "      #footer .wrap>div {\n"
                + "        width: 30%;\n"
                + "      }\n"
                + "\n"
                + "      #footer h5 {\n"
                + "        font-size: 30px;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width:1250px) {\n"
                + "\n"
                + "      .wrap {\n"
                + "        width: 90%;\n"
                + "        margin: 0px auto;\n"
                + "      }\n"
                + "\n"
                + "      #footer .wrap>div {\n"
                + "        width: 30%;\n"
                + "      }\n"
                + "\n"
                + "      #footer h5 {\n"
                + "        font-size: 22px;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 1080px) {\n"
                + "      #footer .wrap>div {\n"
                + "        width: 30%;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 970px) {\n"
                + "      #footer .wrap>div {\n"
                + "        width: 26%;\n"
                + "        margin: 20px;\n"
                + "\n"
                + "      }\n"
                + "\n"
                + "      #footer h5 {\n"
                + "        font-size: 20px;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 799px) {\n"
                + "      #banner h1 {\n"
                + "        font-size: 30px;\n"
                + "        display: block;\n"
                + "        text-align: center;\n"
                + "      }\n"
                + "\n"
                + "      #banner h1 {\n"
                + "        width: 200px;\n"
                + "      }\n"
                + "\n"
                + "      .card {\n"
                + "        height: auto;\n"
                + "      }\n"
                + "\n"
                + "      #footer img {\n"
                + "        margin-bottom: 15px;\n"
                + "        max-width: 100%;\n"
                + "      }\n"
                + "\n"
                + "      #footer .wrap>div {\n"
                + "        width: 100%;\n"
                + "        margin: 0px auto;\n"
                + "        margin-top: 20px;\n"
                + "      }\n"
                + "\n"
                + "      #footer {\n"
                + "        height: auto;\n"
                + "        padding-bottom: 40px;\n"
                + "      }\n"
                + "\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 600px) {\n"
                + "      #footer {\n"
                + "        height: auto;\n"
                + "        padding-bottom: 40px;\n"
                + "      }\n"
                + "\n"
                + "      #footer .wrap>div {\n"
                + "        width: 100%;\n"
                + "        margin: 0px auto;\n"
                + "        margin-top: 20px;\n"
                + "      }\n"
                + "\n"
                + "      #footer h5 {\n"
                + "        font-size: 25px;\n"
                + "      }\n"
                + "\n"
                + "      .tbl-content table tr {\n"
                + "        display: block;\n"
                + "        border-bottom: 5px solid black;\n"
                + "        background-color: #f8f8f8;\n"
                + "      }\n"
                + "\n"
                + "      .tbl-content table td {\n"
                + "        display: block;\n"
                + "        text-align: right;\n"
                + "         border-bottom: 1px solid #ddd;\n"
                + "      }\n"
                + "\n"
                + "    }\n"
                + "  </style>";

        body = "<section class=\"wrap\">\n"
                + "\n"
                + "      <div id=\"banner\">\n"
                + "        <h1>" + HtmlVars.TITULO_SW + "</h1>\n"
                + "        <div class=\"banner-photo\"></div>\n"
                + "      </div>\n"
                + "\n"
                + "      <div class=\"tbl-header\">\n"
                + "        <h1>" + title + "</h1>\n"
                + "        <table>\n"
                + "          <thead>\n"
                + table_headers_html
                + "          </thead>\n"
                + "        </table>\n"
                + "      </div>\n"
                + "\n"
                + "      <div class=\"tbl-content\">\n"
                + "        <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
                + "          <tbody>\n"
                + table_body_html
                + "          </tbody>\n"
                + "        </table>\n"
                + "\n"
                + "      </div>\n"
                + "\n"
                + "      <div class=\"clearfix\"></div>\n"
                + "\n"
                + "    </section>";
        return HTML_OPEN + HEAD_OPEN + head + HEAD_CLOSE + BODY_OPEN + body + BODY_CLOSE + HTML_CLOSE;

    }

    public static String generateTableWithPhotos(String title, String[] headers, String[] data, String[] headersPhotos,
            List<String[]> dataPhotos) {
        String body, head, solicitar_comandos, table_headers_html, table_body_html, table_headersPhotos_html,
                table_bodyPhotos_html;
        List<String[]> list = new LinkedList();
        list.add(data);
        solicitar_comandos = HtmlBuilder.generateMailToComand();
        table_headers_html = HtmlBuilder.generateTableHeaders(headers);
        table_body_html = HtmlBuilder.generateTableBody(list);
        table_headersPhotos_html = HtmlBuilder.generateTableHeaders(headersPhotos);
        table_bodyPhotos_html = HtmlBuilder.generateTableBody(dataPhotos);

        head = " <meta charset=\"utf-8\">\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, user-scalable=no\">\n"
                + "  <title>Fixed table header</title>\n"
                + "  <style type=\"text/css\">\n"
                + "    * {\n"
                + "      margin: 0px;\n"
                + "      padding: 0px;\n"
                + "    }\n"
                + "\n"
                + "    section {\n"
                + "      margin: 50px;\n"
                + "    }\n"
                + "\n"
                + "    h1 {\n"
                + "      font-size: 30px;\n"
                + "      color: #ccc;\n"
                + "      text-transform: uppercase;\n"
                + "      font-weight: 300;\n"
                + "      text-align: center;\n"
                + "      margin: 15px;\n"
                + "    }\n"
                + "\n"
                + "    .wrap {\n"
                + "      /* width: 1250px; */\n"
                + "      width: 90%;\n"
                + "      margin: 0px auto;\n"
                + "      padding-bottom: 20px;\n"
                + "    }\n"
                + "\n"
                + "    #banner {\n"
                + "      width: 95.5%;\n"
                + "      height: 100px;\n"
                + "      border: 10px solid black;\n"
                + "      box-shadow: 0px 0px 15px black;\n"
                + "      background: url(\"https://s3service12.s3.amazonaws.com/bakbaner.png\");\n"
                + "      background-position: -200px -200px;\n"
                + "      margin: 20px auto;\n"
                + "      overflow: hidden;\n"
                + "    }\n"
                + "\n"
                + "    #banner h1 {\n"
                + "      display: block;\n"
                + "      width: 850px;\n"
                + "      font-family: \"BebasNeue\";\n"
                + "      color: white;\n"
                + "      font-size: 45px;\n"
                + "      font-weight: normal;\n"
                + "      letter-spacing: 2px;\n"
                + "      text-shadow: 2px 2px 1px black;\n"
                + "      margin: 27px auto;\n"
                + "    }\n"
                + "\n"
                + "    td > .titulo{\n"
                + "      \n"
                + "      /* margin-bottom: -70px; */\n"
                + "    }\n"
                + "    td > .titulo > img{\n"
                + "      height: 200px; \n"
                + "      width: 200px;\n"
                + "      margin: 0px;\n"
                + "    }\n"
                + "    \n"
                + "    .titulo {\n"
                + "      height: 280px;\n"
                + "      /* margin: 50px auto; */\n"
                + "    }\n"
                + "\n"
                + "    .titulo img {\n"
                + "      height: 100%;\n"
                + "      display: block;\n"
                + "      margin: 0 auto;\n"
                + "      border: 5px solid black;\n"
                + "      border-radius: 25px;\n"
                + "    }\n"
                + "\n"
                + "    table {\n"
                + "      width: 100%;\n"
                + "      table-layout: fixed;\n"
                + "      border-collapse: collapse;\n"
                + "      margin: 0;\n"
                + "      padding: 0;\n"
                + "    }\n"
                + "\n"
                + "    th {\n"
                + "      overflow-x: auto;\n"
                + "      padding: 20px 15px;\n"
                + "      text-align: left;\n"
                + "      font-weight: 500;\n"
                + "      font-size: 20px;\n"
                + "      color: white;\n"
                + "      text-transform: uppercase;\n"
                + "    }\n"
                + "\n"
                + "    td {\n"
                + "      padding: 15px;\n"
                + "      text-align: left;\n"
                + "      vertical-align: middle;\n"
                + "      font-weight: 300;\n"
                + "      font-size: 18px;\n"
                + "      color: black;\n"
                + "      border-bottom: solid 1px black;\n"
                + "    }\n"
                + "\n"
                + "    .tbl-header {\n"
                + "      display: block;\n"
                + "      overflow-y: auto;\n"
                + "      padding-top: 10px;\n"
                + "      margin-top: 50px;\n"
                + "      background-color: black;\n"
                + "    }\n"
                + "\n"
                + "    .tbl-content {\n"
                + "      display: block;\n"
                + "      overflow-x: auto;\n"
                + "      /* height: 150px; */\n"
                + "      border: 3px solid black;\n"
                + "      background-color: #f8f8f8;\n"
                + "    }\n"
                + "\n"
                + "    .class-button {\n"
                + "      margin: 5px;\n"
                + "      padding: 10px;\n"
                + "      border-radius: 10cm;\n"
                + "      border: 3px solid gray;\n"
                + "      text-decoration: none;\n"
                + "      display: inline-block;\n"
                + "      background: black;\n"
                + "      text-align: center;\n"
                + "      line-height: 2;\n"
                + "      color: white;\n"
                + "    }\n"
                + "\n"
                + "    .clearfix {\n"
                + "      float: none;\n"
                + "      clear: both;\n"
                + "    }\n"
                + "\n"
                + "    #footer {\n"
                + "      width: 100%;\n"
                + "      height: 470px;\n"
                + "      background: black;\n"
                + "      color: white;\n"
                + "      overflow: hidden;\n"
                + "      margin-top: 20px;\n"
                + "    }\n"
                + "\n"
                + "    #footer .wrap>div {\n"
                + "      float: left;\n"
                + "      width: 30%;\n"
                + "      /* width: 300px; */\n"
                + "      /* height: 370px; */\n"
                + "      margin: 3% 1%;\n"
                + "      /* margin: 60px 40px; */\n"
                + "      text-align: center;\n"
                + "      color: white;\n"
                + "    }\n"
                + "\n"
                + "\n"
                + "\n"
                + "    #footer a {\n"
                + "      text-decoration: none;\n"
                + "      color: #37bcf9;\n"
                + "      transition: all 300ms;\n"
                + "    }\n"
                + "\n"
                + "    #footer h5 {\n"
                + "      display: block;\n"
                + "      background: white;\n"
                + "      height: 50px;\n"
                + "      letter-spacing: 2px;\n"
                + "      text-align: center;\n"
                + "      font-size: 25px;\n"
                + "      line-height: 55px;\n"
                + "      color: black;\n"
                + "      border-radius: 5px;\n"
                + "      margin-bottom: 15px;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul {\n"
                + "      text-align: left;\n"
                + "      margin: 20px;\n"
                + "      font-size: 25px;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul li {\n"
                + "      margin-top: 10px;\n"
                + "      padding: 5px;\n"
                + "      border-bottom: 1px solid #ccc;\n"
                + "    }\n"
                + "\n"
                + "    #footer img {\n"
                + "      margin-bottom: 15px;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul li a {\n"
                + "      display: block;\n"
                + "      height: 40px;\n"
                + "      transition: all 300ms;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul li:hover a {\n"
                + "      padding-left: 40px;\n"
                + "      color: white;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    #footer #browsers img {\n"
                + "      width: 45px;\n"
                + "    }\n"
                + "\n"
                + "    #info img {\n"
                + "      width: 150px;\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width:1500px) {\n"
                + "      .wrap {\n"
                + "        width: 90%;\n"
                + "        margin: 0px auto;\n"
                + "      }\n"
                + "\n"
                + "      #footer .wrap>div {\n"
                + "        width: 30%;\n"
                + "      }\n"
                + "\n"
                + "      #footer h5 {\n"
                + "        font-size: 30px;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width:1250px) {\n"
                + "\n"
                + "      .wrap {\n"
                + "        width: 90%;\n"
                + "        margin: 0px auto;\n"
                + "      }\n"
                + "\n"
                + "      #footer .wrap>div {\n"
                + "        width: 30%;\n"
                + "      }\n"
                + "\n"
                + "      #footer h5 {\n"
                + "        font-size: 22px;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 1080px) {\n"
                + "      #footer .wrap>div {\n"
                + "        width: 30%;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 970px) {\n"
                + "      #footer .wrap>div {\n"
                + "        width: 26%;\n"
                + "        margin: 20px;\n"
                + "\n"
                + "      }\n"
                + "\n"
                + "      #footer h5 {\n"
                + "        font-size: 20px;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 799px) {\n"
                + "      #banner h1 {\n"
                + "        font-size: 30px;\n"
                + "        display: block;\n"
                + "        text-align: center;\n"
                + "      }\n"
                + "\n"
                + "      #banner h1 {\n"
                + "        width: 200px;\n"
                + "      }\n"
                + "\n"
                + "      .card {\n"
                + "        height: auto;\n"
                + "      }\n"
                + "\n"
                + "      #footer img {\n"
                + "        margin-bottom: 15px;\n"
                + "        max-width: 100%;\n"
                + "      }\n"
                + "\n"
                + "      #footer .wrap>div {\n"
                + "        width: 100%;\n"
                + "        margin: 0px auto;\n"
                + "        margin-top: 20px;\n"
                + "      }\n"
                + "\n"
                + "      #footer {\n"
                + "        height: auto;\n"
                + "        padding-bottom: 40px;\n"
                + "      }\n"
                + "\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 600px) {\n"
                + "      #footer {\n"
                + "        height: auto;\n"
                + "        padding-bottom: 40px;\n"
                + "      }\n"
                + "\n"
                + "      #footer .wrap>div {\n"
                + "        width: 100%;\n"
                + "        margin: 0px auto;\n"
                + "        margin-top: 20px;\n"
                + "      }\n"
                + "\n"
                + "      #footer h5 {\n"
                + "        font-size: 25px;\n"
                + "      }\n"
                + "\n"
                + "      .tbl-content table tr {\n"
                + "        display: block;\n"
                + "        border-bottom: 5px solid black;\n"
                + "        background-color: #f8f8f8;\n"
                + "      }\n"
                + "\n"
                + "      .tbl-content table td {\n"
                + "        display: block;\n"
                + "        text-align: right;\n"
                + "        border-bottom: 1px solid #ddd;\n"
                + "      }\n"
                + "\n"
                + "    }\n"
                + "  </style>";

        body = "<section class=\"wrap\">\n"
                + "\n"
                + "    <div id=\"banner\">\n"
                + "      <h1>" + HtmlVars.TITULO_SW + "</h1>\n"
                + "    </div>\n"
                + "\n"
                + "    <div class=\"titulo\">\n"
                + "      <img\n"
                + "        src=\"https://scontent.fvvi1-1.fna.fbcdn.net/v/t1.18169-9/14691012_547821868741019_5762955511133398050_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=bC-X6Iq9JosAX_Dw2TK&_nc_ht=scontent.fvvi1-1.fna&oh=00_AfC1wvJIHEGl1RNRO1M7dc-hSOxRhU5Xr4v5Ef23NXqZyA&oe=6392475A\"\n"
                + "        alt=\"\">\n"
                + "    </div>\n"
                + "\n"
                + "    <div class=\"tbl-header\">\n"
                + "      <h1>" + title + "</h1>\n"
                + "      <table>\n"
                + "        <thead>\n"
                + table_headers_html
                + "        </thead>\n"
                + "      </table>\n"
                + "    </div>\n"
                + "\n"
                + "    <div class=\"tbl-content\">\n"
                + "      <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
                + "        <tbody>\n"
                + table_body_html
                + "        </tbody>\n"
                + "      </table>\n"
                + "    </div>\n"
                + "\n"
                + "    <div class=\"tbl-header\">\n"
                + "      <h1>LISTA DE FOTOS</h1>\n"
                + "      <table>\n"
                + "        <thead>\n"
                + table_headersPhotos_html
                + "        </thead>\n"
                + "      </table>\n"
                + "    </div>\n"
                + "\n"
                + "    <div class=\"tbl-content\" style=\"height: 700px;\">\n"
                + "      <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
                + "        <tbody>\n"
                + table_bodyPhotos_html
                + "        </tbody>\n"
                + "      </table>\n"
                + "\n"
                + "    </div>\n"
                + "\n"
                + "    <div class=\"clearfix\"></div>\n"
                + "\n"
                + "    <footer id=\"footer\">\n"
                + "      <div class=\"wrap\">\n"
                + "        <div id=\"menu_footer\">\n"
                + "          <h5>MENÚ</h5>\n"
                + "          <ul>\n"
                + "            <li> <a href=\"" + solicitar_comandos + "\">Solicitar Comandos</a> </li>\n"
                + "            <li> <a href=\"#\">Blog</a> </li>\n"
                + "            <li> <a href=\"#\">Formacion</a> </li>\n"
                + "            <li> <a href=\"#\">Contacto</a> </li>\n"
                + "          </ul>\n"
                + "        </div>\n"
                + "\n"
                + "        <div id=\"location\">\n"
                + "          <h5>¿DONDE ESTAMOS?</h5>\n"
                + "          <img height=\"250\" width=\"100%\" src=\"https://s3service12.s3.amazonaws.com/1/11.png\" alt=\"ubicacion\">\n"
                + "          <a\n"
                + "            href=\"https://www.google.com/maps/place/+11+TV+Universitaria,+entre+Segundo+y,+Av.+Hernando+Sanabria,+3er+Anillo+Interno,+Santa+Cruz+de+la+Sierra/@-17.7779017,-63.1967581,18z/data=!4m6!3m5!1s0x93f1e800ac8f5041:0xa4380d6ce6ed23a7!8m2!3d-17.7776056!4d-63.1974868!16s%2Fg%2F1z449xg6c\">click\n"
                + "            ubicacion\n"
                + "          </a>\n"
                + "        </div>\n"
                + "\n"
                + "        <div id=\"info\">\n"
                + "          <h5>Desarollado con</h5>\n"
                + "          <p>\n"
                + "            <img src=\"https://www.pikpng.com/pngl/m/150-1506141_html-css-and-javascript-logo-html5-css3-js.png\"\n"
                + "              alt=\"Creado con HTML y CSS\">\n"
                + "          </p>\n"
                + "\n"
                + "          <h5>Optimizado para</h5>\n"
                + "          <p id=\"browsers\">\n"
                + "            <a href=\"#\">\n"
                + "              <img src=\"https://www.freeiconspng.com/thumbs/mozilla-firefox-icon/mozilla-firefox-icon-4.png\"\n"
                + "                alt=\"Firefox\" title=\"Firefox\">\n"
                + "            </a>\n"
                + "\n"
                + "            <a href=\"#\">\n"
                + "              <img src=\"https://www.freeiconspng.com/uploads/google-chrome-icon-6.png\" alt=\"Crome\" title=\"Crome\">\n"
                + "            </a>\n"
                + "\n"
                + "            <a href=\"#\">\n"
                + "              <img src=\"https://cdn-icons-png.flaticon.com/512/6124/6124992.png\" alt=\"Safari\" title=\"Safari\">\n"
                + "            </a>\n"
                + "\n"
                + "            <a href=\"#\">\n"
                + "              <img src=\"https://cdn-icons-png.flaticon.com/512/226/226770.png\" alt=\"android\" title=\"android\">\n"
                + "            </a>\n"
                + "\n"
                + "            <a href=\"#\">\n"
                + "              <img src=\"https://www.freeiconspng.com/thumbs/ios-png/os7-style-metro-ui-icon-19.png\" alt=\"Apple\"\n"
                + "                title=\"Apple\">\n"
                + "            </a>\n"
                + "\n"
                + "          </p>\n"
                + "\n"
                + "          <h5>AUTOR</h5>\n"
                + "          <p>&copy; GRUPO-21-SA 2022/2 - WEB.es</p>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "    </footer>\n"
                + "  </section>";
        return HTML_OPEN + HEAD_OPEN + head + HEAD_CLOSE + BODY_OPEN + body + BODY_CLOSE + HTML_CLOSE;

    }

    public static String generateTableReports(String title, String[] headers, List<String[]> data) {
        String body, head, solicitar_comandos, table_headers_html, table_body_html, urlPhoto;

        solicitar_comandos = HtmlBuilder.generateMailToComand();
        table_headers_html = HtmlBuilder.generateTableHeaders(headers);
        table_body_html = HtmlBuilder.generateTableBody(data);
        urlPhoto = HtmlBuilder.generateTableReportsPercentage(data);
        // urlPhoto = "";

        head = "<meta charset=\"utf-8\">\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, user-scalable=no\">\n"
                + "  <title>Fixed table header</title>\n"
                + "  <style type=\"text/css\">\n"
                + "    * {\n"
                + "      margin: 0px;\n"
                + "      padding: 0px;\n"
                + "    }\n"
                + "\n"
                + "    section {\n"
                + "      margin: 50px;\n"
                + "    }\n"
                + "\n"
                + "    h1 {\n"
                + "      font-size: 30px;\n"
                + "      color: #ccc;\n"
                + "      text-transform: uppercase;\n"
                + "      font-weight: 300;\n"
                + "      text-align: center;\n"
                + "      margin: 15px;\n"
                + "    }\n"
                + "\n"
                + "    .wrap {\n"
                + "      /* width: 1250px; */\n"
                + "      width: 90%;\n"
                + "      margin: 0px auto;\n"
                + "      padding-bottom: 20px;\n"
                + "    }\n"
                + "\n"
                + "    #banner {\n"
                + "      width: 95.5%;\n"
                + "      height: 100px;\n"
                + "      border: 10px solid black;\n"
                + "      box-shadow: 0px 0px 15px black;\n"
                + "      background: url(\"https://s3service12.s3.amazonaws.com/bakbaner.png\");\n"
                + "      background-position: -200px -200px;\n"
                + "      margin: 20px auto;\n"
                + "      overflow: hidden;\n"
                + "    }\n"
                + "\n"
                + "    #banner h1 {\n"
                + "      display: block;\n"
                + "      width: 850px;\n"
                + "      font-family: \"BebasNeue\";\n"
                + "      color: white;\n"
                + "      font-size: 45px;\n"
                + "      font-weight: normal;\n"
                + "      letter-spacing: 2px;\n"
                + "      text-shadow: 2px 2px 1px black;\n"
                + "      margin: 27px auto;\n"
                + "    }\n"
                + "\n"
                + "    #banner>img {\n"
                + "      margin-top: 5px;\n"
                + "      margin-left: 20px;\n"
                + "      float: left;\n"
                + "      width: 80px;\n"
                + "      border: 5px solid black;\n"
                + "      border-radius: 25px;\n"
                + "    }\n"
                + "\n"
                + "    #titulo {\n"
                + "      height: 600px;\n"
                + "      margin: 50px auto;\n"
                + "    }\n"
                + "\n"
                + "    #titulo img {\n"
                + "      height: 100%;\n"
                + "      width: 80%;\n"
                + "      display: block;\n"
                + "      margin: 0 auto;\n"
                + "      border: 5px solid black;\n"
                + "      border-radius: 10px;\n"
                + "    }\n"
                + "\n"
                + "    table {\n"
                + "      width: 100%;\n"
                + "      table-layout: fixed;\n"
                + "      border-collapse: collapse;\n"
                + "      margin: 0;\n"
                + "      padding: 0;\n"
                + "    }\n"
                + "\n"
                + "    th {\n"
                + "      overflow-x: auto;\n"
                + "      padding: 20px 15px;\n"
                + "      text-align: left;\n"
                + "      font-weight: 500;\n"
                + "      font-size: 20px;\n"
                + "      color: white;\n"
                + "      text-transform: uppercase;\n"
                + "    }\n"
                + "\n"
                + "    td {\n"
                + "      padding: 15px;\n"
                + "      text-align: left;\n"
                + "      vertical-align: middle;\n"
                + "      font-weight: 300;\n"
                + "      font-size: 18px;\n"
                + "      color: black;\n"
                + "      border-bottom: solid 1px black;\n"
                + "    }\n"
                + "\n"
                + "    .tbl-header {\n"
                + "      display: block;\n"
                + "      overflow-y: auto;\n"
                + "      padding-top: 10px;\n"
                + "      background-color: black;\n"
                + "    }\n"
                + "\n"
                + "    .tbl-content {\n"
                + "      display: block;\n"
                + "      overflow-x: auto;\n"
                + "      height: 500px;\n"
                + "      border: 3px solid black;\n"
                + "      background-color: #f8f8f8;\n"
                + "    }\n"
                + "\n"
                + "    .class-button {\n"
                + "      margin: 5px;\n"
                + "      padding: 10px;\n"
                + "      border-radius: 10cm;\n"
                + "      border: 3px solid gray;\n"
                + "      text-decoration: none;\n"
                + "      display: inline-block;\n"
                + "      background: black;\n"
                + "      text-align: center;\n"
                + "      line-height: 2;\n"
                + "      color: white;\n"
                + "    }\n"
                + "\n"
                + "    .clearfix {\n"
                + "      float: none;\n"
                + "      clear: both;\n"
                + "    }\n"
                + "\n"
                + "    #footer {\n"
                + "      width: 100%;\n"
                + "      height: 470px;\n"
                + "      background: black;\n"
                + "      color: white;\n"
                + "      overflow: hidden;\n"
                + "      margin-top: 20px;\n"
                + "    }\n"
                + "\n"
                + "    #footer .wrap>div {\n"
                + "      float: left;\n"
                + "      width: 30%;\n"
                + "      /* width: 300px; */\n"
                + "      /* height: 370px; */\n"
                + "      margin: 3% 1%;\n"
                + "      /* margin: 60px 40px; */\n"
                + "      text-align: center;\n"
                + "      color: white;\n"
                + "    }\n"
                + "\n"
                + "\n"
                + "\n"
                + "    #footer a {\n"
                + "      text-decoration: none;\n"
                + "      color: #37bcf9;\n"
                + "      transition: all 300ms;\n"
                + "    }\n"
                + "\n"
                + "    #footer h5 {\n"
                + "      display: block;\n"
                + "      background: white;\n"
                + "      height: 50px;\n"
                + "      letter-spacing: 2px;\n"
                + "      text-align: center;\n"
                + "      font-size: 25px;\n"
                + "      line-height: 55px;\n"
                + "      color: black;\n"
                + "      border-radius: 5px;\n"
                + "      margin-bottom: 15px;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul {\n"
                + "      text-align: left;\n"
                + "      margin: 20px;\n"
                + "      font-size: 25px;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul li {\n"
                + "      margin-top: 10px;\n"
                + "      padding: 5px;\n"
                + "      border-bottom: 1px solid #ccc;\n"
                + "    }\n"
                + "\n"
                + "    #footer img {\n"
                + "      margin-bottom: 15px;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul li a {\n"
                + "      display: block;\n"
                + "      height: 40px;\n"
                + "      transition: all 300ms;\n"
                + "    }\n"
                + "\n"
                + "    #footer ul li:hover a {\n"
                + "      padding-left: 40px;\n"
                + "      color: white;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    #footer #browsers img {\n"
                + "      width: 45px;\n"
                + "    }\n"
                + "\n"
                + "    #info img {\n"
                + "      width: 150px;\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width:1500px) {\n"
                + "\n"
                + "      #titulo {\n"
                + "        height: 500px;\n"
                + "      }\n"
                + "\n"
                + "      .wrap {\n"
                + "        width: 90%;\n"
                + "        margin: 0px auto;\n"
                + "      }\n"
                + "\n"
                + "      #footer .wrap>div {\n"
                + "        width: 30%;\n"
                + "      }\n"
                + "\n"
                + "      #footer h5 {\n"
                + "        font-size: 30px;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width:1250px) {\n"
                + "      #titulo {\n"
                + "        height: 350px;\n"
                + "      }\n"
                + "\n"
                + "      .wrap {\n"
                + "        width: 90%;\n"
                + "        margin: 0px auto;\n"
                + "      }\n"
                + "\n"
                + "      #footer .wrap>div {\n"
                + "        width: 30%;\n"
                + "      }\n"
                + "\n"
                + "      #footer h5 {\n"
                + "        font-size: 22px;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 1080px) {\n"
                + "      #titulo {\n"
                + "        height: 300px;\n"
                + "      }\n"
                + "\n"
                + "      #footer .wrap>div {\n"
                + "        width: 30%;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 970px) {\n"
                + "      #titulo {\n"
                + "        height: 275px;\n"
                + "      }\n"
                + "\n"
                + "      #footer .wrap>div {\n"
                + "        width: 26%;\n"
                + "        margin: 20px;\n"
                + "\n"
                + "      }\n"
                + "\n"
                + "      #footer h5 {\n"
                + "        font-size: 20px;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 799px) {\n"
                + "      #titulo {\n"
                + "        height: 250px;\n"
                + "      }\n"
                + "\n"
                + "      #banner h1 {\n"
                + "        font-size: 30px;\n"
                + "        display: block;\n"
                + "        text-align: center;\n"
                + "      }\n"
                + "\n"
                + "      #banner h1 {\n"
                + "        width: 200px;\n"
                + "      }\n"
                + "\n"
                + "      .card {\n"
                + "        height: auto;\n"
                + "      }\n"
                + "\n"
                + "      #footer img {\n"
                + "        margin-bottom: 15px;\n"
                + "        max-width: 100%;\n"
                + "      }\n"
                + "\n"
                + "      #footer .wrap>div {\n"
                + "        width: 100%;\n"
                + "        margin: 0px auto;\n"
                + "        margin-top: 20px;\n"
                + "      }\n"
                + "\n"
                + "      #footer {\n"
                + "        height: auto;\n"
                + "        padding-bottom: 40px;\n"
                + "      }\n"
                + "\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 650px) {\n"
                + "      #titulo {\n"
                + "        height: 225px;\n"
                + "      }\n"
                + "      #footer {\n"
                + "        height: auto;\n"
                + "        padding-bottom: 40px;\n"
                + "      }\n"
                + "\n"
                + "      #footer .wrap>div {\n"
                + "        width: 100%;\n"
                + "        margin: 0px auto;\n"
                + "        margin-top: 20px;\n"
                + "      }\n"
                + "\n"
                + "      #footer h5 {\n"
                + "        font-size: 25px;\n"
                + "      }\n"
                + "\n"
                + "      .tbl-content table tr {\n"
                + "        display: block;\n"
                + "        border-bottom: 5px solid black;\n"
                + "        background-color: #f8f8f8;\n"
                + "      }\n"
                + "\n"
                + "      .tbl-content table td {\n"
                + "        display: block;\n"
                + "        text-align: right;\n"
                + "        border-bottom: 1px solid #ddd;\n"
                + "      }\n"
                + "\n"
                + "    }\n"
                + "  </style>";

        body = "<section class=\"wrap\">\n"
                + "\n"
                + "    <div id=\"banner\">\n"
                + "      <img\n"
                + "        src=\"https://scontent.fvvi1-1.fna.fbcdn.net/v/t1.18169-9/14691012_547821868741019_5762955511133398050_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=bC-X6Iq9JosAX_Dw2TK&_nc_ht=scontent.fvvi1-1.fna&oh=00_AfC1wvJIHEGl1RNRO1M7dc-hSOxRhU5Xr4v5Ef23NXqZyA&oe=6392475A\"\n"
                + "        alt=\"\">\n"
                + "      <h1>" + HtmlVars.TITULO_SW + "</h1>\n"
                + "    </div>\n"
                + "\n"
                + "    <div id=\"titulo\">\n"
                + "\n"
                + "      <img\n"
                + "        src=\"" + urlPhoto + "\"\n"
                + "        alt=\"\">\n"
                + "    </div>\n"
                + "\n"
                + "    <div class=\"tbl-header\">\n"
                + "      <h1>" + title + "</h1>\n"
                + "      <table>\n"
                + "        <thead>\n"
                + table_headers_html
                + "        </thead>\n"
                + "      </table>\n"
                + "    </div>\n"
                + "\n"
                + "    <div class=\"tbl-content\">\n"
                + "      <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
                + "        <tbody>\n"
                + table_body_html
                + "        </tbody>\n"
                + "      </table>\n"
                + "\n"
                + "    </div>\n"
                + "\n"
                + "    <div class=\"clearfix\"></div>\n"
                + "\n"
                + "    <footer id=\"footer\">\n"
                + "      <div class=\"wrap\">\n"
                + "        <div id=\"menu_footer\">\n"
                + "          <h5>MENÚ</h5>\n"
                + "          <ul>\n"
                + "            <li> <a href=\"" + solicitar_comandos + "\">Solicitar Comandos</a> </li>\n"
                + "            <li> <a href=\"#\">Blog</a> </li>\n"
                + "            <li> <a href=\"#\">Formacion</a> </li>\n"
                + "            <li> <a href=\"#\">Contacto</a> </li>\n"
                + "          </ul>\n"
                + "        </div>\n"
                + "\n"
                + "        <div id=\"location\">\n"
                + "          <h5>¿DONDE ESTAMOS?</h5>\n"
                + "          <img height=\"250\" width=\"100%\" src=\"https://s3service12.s3.amazonaws.com/1/11.png\" alt=\"ubicacion\">\n"
                + "          <a\n"
                + "            href=\"https://www.google.com/maps/place/+11+TV+Universitaria,+entre+Segundo+y,+Av.+Hernando+Sanabria,+3er+Anillo+Interno,+Santa+Cruz+de+la+Sierra/@-17.7779017,-63.1967581,18z/data=!4m6!3m5!1s0x93f1e800ac8f5041:0xa4380d6ce6ed23a7!8m2!3d-17.7776056!4d-63.1974868!16s%2Fg%2F1z449xg6c\">click\n"
                + "            ubicacion\n"
                + "          </a>\n"
                + "        </div>\n"
                + "\n"
                + "        <div id=\"info\">\n"
                + "          <h5>Desarollado con</h5>\n"
                + "          <p>\n"
                + "            <img src=\"https://www.pikpng.com/pngl/m/150-1506141_html-css-and-javascript-logo-html5-css3-js.png\"\n"
                + "              alt=\"Creado con HTML y CSS\">\n"
                + "          </p>\n"
                + "\n"
                + "          <h5>Optimizado para</h5>\n"
                + "          <p id=\"browsers\">\n"
                + "            <a href=\"#\">\n"
                + "              <img src=\"https://www.freeiconspng.com/thumbs/mozilla-firefox-icon/mozilla-firefox-icon-4.png\"\n"
                + "                alt=\"Firefox\" title=\"Firefox\">\n"
                + "            </a>\n"
                + "\n"
                + "            <a href=\"#\">\n"
                + "              <img src=\"https://www.freeiconspng.com/uploads/google-chrome-icon-6.png\" alt=\"Crome\" title=\"Crome\">\n"
                + "            </a>\n"
                + "\n"
                + "            <a href=\"#\">\n"
                + "              <img src=\"https://cdn-icons-png.flaticon.com/512/6124/6124992.png\" alt=\"Safari\" title=\"Safari\">\n"
                + "            </a>\n"
                + "\n"
                + "            <a href=\"#\">\n"
                + "              <img src=\"https://cdn-icons-png.flaticon.com/512/226/226770.png\" alt=\"android\" title=\"android\">\n"
                + "            </a>\n"
                + "\n"
                + "            <a href=\"#\">\n"
                + "              <img src=\"https://www.freeiconspng.com/thumbs/ios-png/os7-style-metro-ui-icon-19.png\" alt=\"Apple\"\n"
                + "                title=\"Apple\">\n"
                + "            </a>\n"
                + "\n"
                + "          </p>\n"
                + "\n"
                + "          <h5>AUTOR</h5>\n"
                + "          <p>&copy; GRUPO-21-SA 2022/2 - WEB.es</p>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "    </footer>\n"
                + "  </section>";
        return HTML_OPEN + HEAD_OPEN + head + HEAD_CLOSE + BODY_OPEN + body + BODY_CLOSE + HTML_CLOSE;

    }

    private static String generateTableReportsPercentage(List<String[]> data) {

        String r, porcentaje, cabecera;
        float s = 0.0f;
        String esp = "%20";
        // r =
        // "http://chart.apis.google.com/chart?chs=400x100&cht=p&chd=t:45,25,10,20&chl=Valencia|Madrid|Barcelona|Lugo\"
        // width=\"400\" height=\"100";
        // r =
        // "https://chart.apis.google.com/chart?chs=700x300&cht=p&chd=t:45,25,10,20&chl=Valencia|Madrid|Barcelona|Lugo%22%20width=%22400%22%20height=%22100%22";
        if (data.size() >= 2) {
            for (String[] fil : data) {
                // System.out.println(fil[1]);
                s = s + Float.parseFloat(fil[2]);
            }
        }
        porcentaje = "";
        cabecera = "";
        r = "";
        if (s > 0) {
            r = "https://chart.apis.google.com/chart?chs=700x300&cht=p&chd=t:";
            for (String[] d : data) {
                double f = (Float.parseFloat(d[2]) * 100 / (float) s);
                f = Math.round(f * 10d) / 10d;
                cabecera += f + "%" + " - " + d[1] + "|";
                porcentaje += f + ",";
            }
            porcentaje = porcentaje.substring(0, porcentaje.length() - 1);
            cabecera = cabecera.substring(0, cabecera.length() - 1);
            r = r + porcentaje + "&chl=" + cabecera;
            // System.out.println(r);
        }

        return r;
    }

    public static String generatePrueba() {
        return "";
    }

}
